[build-system]
requires = ["setuptools>=84", "setuptools-scm==10.3.4"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
fallback_version = "0.0"

[project]
classifiers = [
  "Intended Audience :: Developers",
  "Operating System :: OS Independent",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
]
name = "nomad-distribution"
description = "nomad distribution template"
dynamic = ["version"]
readme = "README.md"
requires-python = ">=3.10"
license = { file = "LICENSE" }
dependencies = [
  "nomad-lab[infrastructure]==1.4.2",
  "setuptools==84.0.0",
  "fastapi==0.136.3",
]


[project.urls]
repository = "https://github.com/zbt-tools/nomad-oasis"

[project.optional-dependencies]
plugins = [
  "nomad-north-jupyter==0.2.6",
  "perovskite-solar-cell-database @ git+https://github.com/FAIRmat-NFDI/nomad-perovskite-solar-cells-database.git@v1.2.15",
  "nomad-porous-materials @ git+https://github.com/FAIRmat-NFDI/nomad-porous-materials.git@b07ec28178dbbd7e7c55c0eba040a697d90e6bba",
  "nomad-aitoolkit @ git+https://github.com/FAIRmat-NFDI/nomad-aitoolkit.git@v0.2.0",
  "nomad-simulations==0.8.0",
  "pynxtools==0.15.2",
  "pynxtools-apm==0.5.3",
  "pynxtools-ellips==0.1.3",
  "pynxtools-em==0.4.6",
  "pynxtools-igor==0.1.6",
  "pynxtools-mpes==0.2.8",
  "pynxtools-raman==0.1.3",
  "pynxtools-spm==0.4.0",
  "pynxtools-xps==0.6.2",
  "pynxtools-xrd==0.0.8",
  "nomad-schema-plugin-run==1.0.5",
  "nomad-schema-plugin-simulation-workflow==1.0.11",
  "nomad-normalizer-plugin-bandstructure==1.0.4",
  "nomad-normalizer-plugin-dos==1.0.7",
  "nomad-normalizer-plugin-soap==1.0.2",
  "nomad-normalizer-plugin-spectra==1.0.4",
  "nomad-normalizer-plugin-system==1.0.5",
  "nomad-normalizer-plugin-simulation-workflow==1.0.5",
  "eelsdbconverter @ git+https://github.com/nomad-coe/nomad-parser-eelsdb.git@788eb03dc71ef9b164e2a5ccb9c0209b546f5c38",
  "nomad-parser-plugins-electronic==1.1.0",
  "nomad-parser-plugins-atomistic==1.0.12",
  "nomad-parser-plugins-workflow==1.2.0",
  "nomad-parser-plugins-database==1.1.3",
  "nptdms==1.11.0",
  "nomad-greenlight-plugin @ git+https://github.com/ZBT-Tools/nomad-greenlight-plugin.git@8c5e0f93499feb4a063315175f9a094dde040ac6",
  "nomad-tdms-plugin @ git+https://github.com/ZBT-Tools/nomad-tdms-plugin.git@8f38d4a47b66e6308e83da9d673cc03c8dae08ae",
  "nomad-avl-fire-rdm @ git+https://github.com/ZBT-Tools/nomad-avl-fire-rdm.git@d7c2fcb58eb68aaf6437a67035fc45a935c64aa3",
  "paramiko==5.0.0",
  "lxml==6.1.3",
  "python-dotenv==1.2.3",
  "avl-fire-rdm @ git+https://github.com/ZBT-Tools/AVL-FIRE-RDM.git@62b2b25d7adc1b306788e3cda9c0c5ddbac24f7a",
  "nomad-filter-plugin @ git+https://github.com/ZBT-Tools/nomad-filter-plugin@b4c57f93651885843c42a2cafff0bbc5cba7a2e6",
  "nomad-measurements @ git+https://github.com/FAIRmat-NFDI/nomad-measurements@v1.3.8",
  "nomad-auto-xrd @ git+https://github.com/FAIRmat-NFDI/nomad-auto-xrd@v0.3.9"
]
jupyter = ["jupyter-events==0.12.1"]
gpu-action = []
cpu-action = []

dev = ["nomad-lab[dev, infrastructure]==1.4.2"]

[tool.uv]
extra-index-url = [
  "https://gitlab.mpcdf.mpg.de/api/v4/projects/2187/packages/pypi/simple",
]
prerelease = "explicit"

constraint-dependencies = ["flatdict==4.1.0"]


[tool.setuptools.packages.find]
exclude = ["gui*", "docs*", "config*"]
