# Nginx configuration for handling HTTP requests

map $http_upgrade $connection_upgrade {
    default upgrade;
    ''      close;
}

server {
    listen        1080;
    server_name   172.16.134.9 localhost;
    proxy_set_header Host $http_host;
    proxy_set_header X-Forwarded-Host $http_host;
    proxy_set_header X-Forwarded-Port $server_port;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    
    # location /keycloak {
    #     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    #     proxy_set_header X-Forwarded-Proto $scheme;

    #     rewrite /keycloak/(.*) /$1 break;
    #     proxy_pass http://keycloak:8080;
    # }
    
    include conf.d/nginx_base_conf;
}
